spring.application.name=picpaysimplificado

spring.datasource.url=jdbc:h2:mem:testbd
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.h2.console.enabled=true

transaction.authorization.url=https://run.mocky.io/v3/5794d450-d2e2-4412-8131-73d0293ac1cc